export const ALLIES = [
  {
    name: 'Mirko',
    title: 'Der Banker',
    timing: 'Vor dem Kampf',
    ability: 'Investment Roll',
    desc: 'Mirko würfelt mit beiden Würfeln. Ist die Summe 7 oder höher, verursachen Saschas Treffer in Runde 1 +2 Bonusschaden. Ist die Summe unter 7, verursachen die gegnerischen Treffer in Runde 1 +1 Bonusschaden.',
    mechanic: 'dice',
  },
  {
    name: 'Nick',
    title: 'Der Schurke',
    timing: '2× im gesamten Spiel',
    ability: 'Schattenwurf',
    desc: 'Nick wirft unangekündigt einen Sandsack auf das Ziel \u2014 weder Sascha noch der Gegner dürfen es vorher wissen. Nick entscheidet selbst, wann er zuschlägt. Trifft er, zählt der Treffer als Bonusschaden gegen den Gegner (Außen 1, Mitte 3, Innen 5). Darf insgesamt nur zweimal während des gesamten Spiels eingesetzt werden.',
    mechanic: 'physical',
  },
  {
    name: 'Jess',
    title: 'Die Amazone',
    timing: 'Einmal pro Kampf',
    ability: 'Staffelwurf',
    desc: 'Jess wirft einen Sandsack zusammen mit Sascha \u2014 beide werfen gleichzeitig. Der bessere Treffer zählt.',
    mechanic: 'physical',
  },
  {
    name: 'Der Vater',
    title: 'Oberhaupt der Diebesgilde',
    timing: 'Vor dem Kampf',
    ability: 'Bierverkostung',
    desc: 'Sascha wählt eine von zwei Schwierigkeitsstufen. Extrawürfe in Runde 1 werden nicht von Skills beeinflusst.',
    mechanic: 'challenge',
    deals: [
      { name: 'Normal', cost: 0, desc: 'Zwei Biere (Kölsch & Alt) mit geschlossenen Augen probieren und erraten, welches welches ist.<br>Richtig \u2192 1 Extrawurf.<br>Falsch \u2192 der Gegner erhält 1 Extrawurf.' },
      { name: 'Schwer', cost: 0, desc: 'Zwei Alt-Biere mit geschlossenen Augen probieren und das Füchschen Alt erkennen.<br>Richtig \u2192 2 Extrawürfe.<br>Falsch \u2192 der Gegner erhält 1 Extrawurf.' },
    ],
  },
  {
    name: 'Daniel',
    title: 'Der treue Gefolgsmann',
    timing: 'Einmal pro Kampf',
    ability: 'Leibwächter',
    desc: 'Daniel stellt sich nah an die Zielscheibe. Einmal pro Kampf fängt oder lenkt er den Sandsack des Gegners mit den Händen ab \u2014 dieser Wurf zählt als Fehlwurf.',
    mechanic: 'physical',
  },
  {
    name: 'Lukas',
    title: 'Der Geschäftsmann',
    timing: 'Vor dem Kampf',
    ability: 'Dubiose Deals',
    desc: 'Lukas bietet Deals an, bei denen Sascha HP für einen Vorteil zahlt. Jeweils einmal pro Kampf.',
    mechanic: 'deal',
    deals: [
      { name: 'Insider Info', cost: 4, desc: 'Zahle 4 HP vor dem Kampf \u2192 deaktiviere einen Einsatz des ersten aktiven Skills des Gegners für den Kampf.' },
    ],
  },
];
